
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='traindata',
    version='0.1.0',
    description='Orthography-to-phonlogy tools that preprocess data for training cognitive reading models',
    python_requires='<3.13,>=3.9',
    author='Matt Cooper Borkenhagen',
    author_email='mcooperborkenhagen@fsu.edu',
    license='MIT',
    packages=[],
    package_dir={"": "."},
    package_data={},
    install_requires=['nltk==3.8.1', 'numpy==1.26.1', 'pandas==2.1.2'],
)
